[build]
base = ""
publish = "public"
command = "AWS_LAMBDA_FUNCTION_NAME=trickpuppeteer npm run build"

[[redirects]]
from = "/preview/articles/:uid/"
to = "/.netlify/functions/preview"
status = 200
force = true
_generated_by_eleventy_serverless = "preview"

[[redirects]]
from = "/learnwebdev/"
to = "https://learnfromsteph.dev"
status = 301

[[redirects]]
from = "/feed/"
to = "/feed/feed.xml"
status = 200
force = true

[dev]
command = "npm start"
