[build]
base = ""
publish = "public"
command = "AWS_LAMBDA_FUNCTION_NAME=trickpuppeteer npm run build"

[[redirects]]
from = "/preview/:uid/"
to = "/.netlify/functions/preview"
status = 200
force = true
_generated_by_eleventy_serverless = "preview"

[[redirects]]
from = "/learnwebdev/"
to = "https://learnfromsteph.dev"
status = 301

[dev]
command = "npm start"
